# Copyright (c) 2026 0x208u16
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---  # Denotes the start of this YAML document. https://yaml.org/spec/1.2/spec.html#id2760395
name: SheepMerge
main: dev.x208.sheepmerge.SheepMergePlugin
version: 0.6.1
api-version: "1.20"
commands:
  sheepmerge:
    description: Teleports you to your sheep farm world and manages your merge game
    usage: /sheepmerge [help|-help|upgrade|prestige|shop|top|status|stats|checkpoints|checkquestpoints|checkprestige|visit|kick|storm|summon|combofrenzy|reload|leaderboard|resetdata|givepoints|giveautomationpoints|setpoints|givequestpoints|setquestpoints|setprestige|world|world save|world load]
... # Denotes the end of this YAML document. https://yaml.org/spec/1.2/spec.html#id2760395